//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Spedicija
{
    using System;
    using System.Collections.Generic;
    
    public partial class DnevnicaDetail
    {
        public int IdDnevnicaDetail { get; set; }
        public int IdVozacDnevnica { get; set; }
        public Nullable<decimal> Dnevnica { get; set; }
        public Nullable<decimal> Nocenje { get; set; }
        public Nullable<decimal> OstaliTroskovi { get; set; }
        public string Napomena { get; set; }
        public Nullable<decimal> Ukupno { get; set; }
        public bool Isplaceno { get; set; }
        public System.DateTime Datum { get; set; }
    
        public virtual VozacDnevnica VozacDnevnica { get; set; }
    }
}
