//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Spedicija
{
    using System;
    using System.Collections.Generic;
    
    public partial class DnevnikPrevoza
    {
        public DnevnikPrevoza()
        {
            this.Troskovi = new HashSet<Troskovi>();
            this.NalogZaUtovar = new HashSet<NalogZaUtovar>();
            this.Dokument = new HashSet<Dokument>();
            this.IzracunDnevnik = new HashSet<IzracunDnevnik>();
            this.DnevnikCarina = new HashSet<DnevnikCarina>();
            this.DnevnikIstovar = new HashSet<DnevnikIstovar>();
            this.DnevnikUtovar = new HashSet<DnevnikUtovar>();
            this.DnevnikUvoznikIzvoznik = new HashSet<DnevnikUvoznikIzvoznik>();
            this.DnevnikValute = new HashSet<DnevnikValute>();
            this.AndroidTask = new HashSet<AndroidTask>();
            this.IDnevnikPrevozaVozac = new HashSet<IDnevnikPrevozaVozac>();
            this.RedoslijedUtovarIstovar = new HashSet<RedoslijedUtovarIstovar>();
        }
    
        public int IdDnevnik { get; set; }
        public Nullable<System.DateTime> DatumDnevnika { get; set; }
        public Nullable<int> IdNarucioca { get; set; }
        public string BrojNaloga { get; set; }
        public string UtovarAdresa { get; set; }
        public string UtovarFirma { get; set; }
        public string UtovarGrad { get; set; }
        public Nullable<System.DateTime> DatumUtovara { get; set; }
        public string IstovarAdresa { get; set; }
        public string IstovarFirma { get; set; }
        public string IstovarGrad { get; set; }
        public Nullable<System.DateTime> DatumIstovara { get; set; }
        public string KolicinaRobe { get; set; }
        public Nullable<decimal> CijenaPrevoza { get; set; }
        public Nullable<int> IdValuta { get; set; }
        public Nullable<int> ValutaPlacanja { get; set; }
        public string UvoznaSpedicija { get; set; }
        public string IzvoznaSpedicija { get; set; }
        public Nullable<int> IdVozilo { get; set; }
        public Nullable<int> IdVozac { get; set; }
        public Nullable<bool> DrugiPrevoznik { get; set; }
        public Nullable<int> IdSubjekt { get; set; }
        public string BrojNalogaPrevoznika { get; set; }
        public Nullable<decimal> CijenaPrevozaPrevoznika { get; set; }
        public Nullable<int> IdValutaPrevoznika { get; set; }
        public string BrojFakture { get; set; }
        public Nullable<System.DateTime> DatumSlanjaFakture { get; set; }
        public Nullable<System.DateTime> DatumZapisa { get; set; }
        public Nullable<bool> ZapisAktivan { get; set; }
        public string SerijskiBroj { get; set; }
        public string VrstaRobe { get; set; }
        public string RegistracijaVozilaPrevoznika { get; set; }
        public string VozacPrevoznika { get; set; }
        public string KontaktOsobaPrevoznika { get; set; }
        public string Status { get; set; }
        public string Napomena { get; set; }
        public Nullable<int> IdPrikljucnoVozilo { get; set; }
        public string Uvoznik { get; set; }
        public string Izvoznik { get; set; }
        public Nullable<int> ValutaPlacanjaPrevoznika { get; set; }
        public Nullable<bool> SaPDV { get; set; }
        public string UtovarKontakt { get; set; }
        public string IstovarKontakt { get; set; }
        public string GostPristup { get; set; }
        public Nullable<bool> Uplaceno { get; set; }
        public Nullable<bool> KompletanUtovar { get; set; }
        public string InternaNapomena { get; set; }
        public string TezinaRobe { get; set; }
        public string PrevoznikIstovarAdresa { get; set; }
        public string PrevoznikIstovarFirma { get; set; }
        public string PrevoznikIstovarGrad { get; set; }
        public string PrevoznikIstovarPTT { get; set; }
        public string PrevoznikIstovarDrzava { get; set; }
        public Nullable<decimal> IznosPDV { get; set; }
        public string UtovarPTT { get; set; }
        public string UtovarDrzava { get; set; }
        public string IstovarPTT { get; set; }
        public string IstovarDrzava { get; set; }
        public string DimenzijeRobe { get; set; }
        public string PrevoznikUtovarFirma { get; set; }
        public string PrevoznikUtovarAdresa { get; set; }
        public string PrevoznikUtovarGrad { get; set; }
        public string PrevoznikUtovarPTT { get; set; }
        public string PrevoznikUtovarDrzava { get; set; }
        public string IstovarKolicinaRobe { get; set; }
        public string ReferentniBrojUtovara { get; set; }
        public Nullable<int> IdDnevnikParent { get; set; }
        public string LONG { get; set; }
        public string LAT { get; set; }
        public string DrugiPrevoznikStatus { get; set; }
        public Nullable<int> IdPonuda { get; set; }
        public Nullable<int> idStatusDetaljni { get; set; }
        public string StatusDetaljniOpis { get; set; }
    
        public virtual ICollection<Troskovi> Troskovi { get; set; }
        public virtual ICollection<NalogZaUtovar> NalogZaUtovar { get; set; }
        public virtual ICollection<Dokument> Dokument { get; set; }
        public virtual Subjekt Subjekt { get; set; }
        public virtual Subjekt Subjekt1 { get; set; }
        public virtual Valuta Valuta { get; set; }
        public virtual Valuta Valuta1 { get; set; }
        public virtual Vozaci Vozaci { get; set; }
        public virtual Vozilo Vozilo { get; set; }
        public virtual ICollection<IzracunDnevnik> IzracunDnevnik { get; set; }
        public virtual Vozilo Vozilo1 { get; set; }
        public virtual ICollection<DnevnikCarina> DnevnikCarina { get; set; }
        public virtual ICollection<DnevnikIstovar> DnevnikIstovar { get; set; }
        public virtual ICollection<DnevnikUtovar> DnevnikUtovar { get; set; }
        public virtual ICollection<DnevnikUvoznikIzvoznik> DnevnikUvoznikIzvoznik { get; set; }
        public virtual ICollection<DnevnikValute> DnevnikValute { get; set; }
        public virtual ICollection<AndroidTask> AndroidTask { get; set; }
        public virtual Ponuda Ponuda { get; set; }
        public virtual StatusRobe StatusRobe { get; set; }
        public virtual ICollection<IDnevnikPrevozaVozac> IDnevnikPrevozaVozac { get; set; }
        public virtual ICollection<RedoslijedUtovarIstovar> RedoslijedUtovarIstovar { get; set; }
    }
}
