//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Spedicija
{
    using System;
    using System.Collections.Generic;
    
    public partial class DnevnikValute
    {
        public int IdDnevnikValute { get; set; }
        public int IdDnevnik { get; set; }
        public System.DateTime DatumAktivnosti { get; set; }
        public string Aktivnost { get; set; }
        public string Detalji { get; set; }
    
        public virtual DnevnikPrevoza DnevnikPrevoza { get; set; }
    }
}
