//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Spedicija
{
    using System;
    using System.Collections.Generic;
    
    public partial class DokumentShare
    {
        public int IdDokumentShare { get; set; }
        public int IdDokument { get; set; }
        public string Kod { get; set; }
    
        public virtual Dokument Dokument { get; set; }
    }
}
