//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Spedicija
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dokument
    {
        public Dokument()
        {
            this.DokumentShare = new HashSet<DokumentShare>();
        }
    
        public int IdDokument { get; set; }
        public string Tip { get; set; }
        public string Putanja { get; set; }
        public Nullable<int> IdDnevnik { get; set; }
        public string Velicina { get; set; }
        public string Naziv { get; set; }
        public Nullable<int> IdVozac { get; set; }
        public Nullable<int> IdVozilo { get; set; }
    
        public virtual DnevnikPrevoza DnevnikPrevoza { get; set; }
        public virtual ICollection<DokumentShare> DokumentShare { get; set; }
    }
}
