//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Spedicija
{
    using System;
    using System.Collections.Generic;
    
    public partial class Grad
    {
        public int IdGrad { get; set; }
        public string Drzava { get; set; }
        public string ISO { get; set; }
        public string Grad1 { get; set; }
    }
}
