//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Spedicija
{
    using System;
    using System.Collections.Generic;
    
    public partial class IDnevnikPrevozaVozac
    {
        public int IdIDnevnikPrevozaVozac { get; set; }
        public System.DateTime DatumOd { get; set; }
        public System.DateTime DatumDo { get; set; }
        public System.DateTime DatumZapisa { get; set; }
        public int IdVozac { get; set; }
        public int IdDnevnik { get; set; }
        public Nullable<int> IdVozilo { get; set; }
    
        public virtual DnevnikPrevoza DnevnikPrevoza { get; set; }
        public virtual Vozaci Vozaci { get; set; }
        public virtual Vozilo Vozilo { get; set; }
    }
}
