//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Spedicija
{
    using System;
    using System.Collections.Generic;
    
    public partial class IzracunZarada
    {
        public IzracunZarada()
        {
            this.IzracunDnevnik = new HashSet<IzracunDnevnik>();
            this.IzracunTrosak = new HashSet<IzracunTrosak>();
        }
    
        public int IdIzracunZarada { get; set; }
        public string Naziv { get; set; }
        public System.DateTime DatumZapisa { get; set; }
        public Nullable<bool> ZapisAktivan { get; set; }
    
        public virtual ICollection<IzracunDnevnik> IzracunDnevnik { get; set; }
        public virtual ICollection<IzracunTrosak> IzracunTrosak { get; set; }
    }
}
