//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Spedicija
{
    using System;
    using System.Collections.Generic;
    
    public partial class Korisnik
    {
        public Korisnik()
        {
            this.Log = new HashSet<Log>();
        }
    
        public int IdKorisnik { get; set; }
        public string KorisnickoIme { get; set; }
        public string Lozinka { get; set; }
        public Nullable<System.DateTime> DatumKreiranja { get; set; }
        public Nullable<System.DateTime> PoslednjaPrijava { get; set; }
        public string IPAdresa { get; set; }
        public Nullable<bool> ZapisAktivan { get; set; }
        public string Role { get; set; }
        public string Ime { get; set; }
        public string Token { get; set; }
    
        public virtual ICollection<Log> Log { get; set; }
    }
}
