//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Spedicija
{
    using System;
    using System.Collections.Generic;
    
    public partial class KorisnikUpit
    {
        public int IdKorisnikUpit { get; set; }
        public string Utovar { get; set; }
        public string Istovar { get; set; }
        public string KolicinaRobe { get; set; }
        public string VrijednostRobe { get; set; }
        public string VrstaRobe { get; set; }
        public Nullable<System.DateTime> DatumUtovara { get; set; }
        public Nullable<System.DateTime> DatumIstovara { get; set; }
        public string ImeKorisnika { get; set; }
        public string Email { get; set; }
        public string Telefon { get; set; }
        public string Napomena { get; set; }
    }
}
