//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Spedicija
{
    using System;
    using System.Collections.Generic;
    
    public partial class KorisnikNalog
    {
        public KorisnikNalog()
        {
            this.KorisnikNalogIstovar = new HashSet<KorisnikNalogIstovar>();
            this.KorisnikNalogUtovar = new HashSet<KorisnikNalogUtovar>();
        }
    
        public int idKorisnikNalog { get; set; }
        public string Naziv { get; set; }
        public string Adresa { get; set; }
        public string Grad { get; set; }
        public string Telefon { get; set; }
        public string Email { get; set; }
        public string KontaktOsoba { get; set; }
        public string Timocom { get; set; }
        public string PIB { get; set; }
        public string Izvoznik { get; set; }
        public string IzvoznikKontaktOsoba { get; set; }
        public string MjestoUtovara { get; set; }
        public Nullable<System.DateTime> DatumUtovara { get; set; }
        public string ReferentniBrojUtovara { get; set; }
        public string VrstaRobe { get; set; }
        public string VrijednostRobe { get; set; }
        public string BrutoTezina { get; set; }
        public string IzvoznaCarina { get; set; }
        public string Uvoznik { get; set; }
        public string UvoznikKontaktOsoba { get; set; }
        public string MjestoIstovara { get; set; }
        public Nullable<System.DateTime> DatumIstovara { get; set; }
        public string UvoznaCarina { get; set; }
        public System.DateTime DatumZahtjeva { get; set; }
        public Nullable<int> IdSubjekt { get; set; }
        public string PTT { get; set; }
        public string Drzava { get; set; }
        public string JIB { get; set; }
        public string FirmaUtovar { get; set; }
        public string FirmaIStovar { get; set; }
        public string PTT1 { get; set; }
        public string Grad1 { get; set; }
        public string Drzava1 { get; set; }
        public string Dimenzije { get; set; }
        public string PTT2 { get; set; }
        public string Grad2 { get; set; }
        public string Drzava2 { get; set; }
    
        public virtual ICollection<KorisnikNalogIstovar> KorisnikNalogIstovar { get; set; }
        public virtual ICollection<KorisnikNalogUtovar> KorisnikNalogUtovar { get; set; }
    }
}
