//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Spedicija
{
    using System;
    using System.Collections.Generic;
    
    public partial class KorisnikNalogUtovar
    {
        public int IdUtovar { get; set; }
        public int IdKorisnikNalog { get; set; }
        public string Firma { get; set; }
        public string Adresa { get; set; }
        public string Mjesto { get; set; }
        public string PTT { get; set; }
        public string Drzava { get; set; }
        public string Kontakt { get; set; }
        public Nullable<System.DateTime> DatmUtovara { get; set; }
        public string KolicinaRobe { get; set; }
        public string VrstaRobe { get; set; }
        public string TezinaRobe { get; set; }
        public string DimenzijeRobe { get; set; }
        public string ReferentniBrojUtovara { get; set; }
        public string IzvoznaCarina { get; set; }
    
        public virtual KorisnikNalog KorisnikNalog { get; set; }
    }
}
