//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Spedicija
{
    using System;
    using System.Collections.Generic;
    
    public partial class Log
    {
        public int IdLog { get; set; }
        public string Tabela { get; set; }
        public Nullable<int> PK { get; set; }
        public Nullable<int> IdKorisnik { get; set; }
        public string Aktivnost { get; set; }
        public Nullable<System.DateTime> Datum { get; set; }
        public string IPAdresa { get; set; }
        public string StaraVrijednost { get; set; }
        public string NovaVrijednost { get; set; }
        public string KorisnickoIme { get; set; }
        public string StatusPromjene { get; set; }
        public Nullable<bool> Pregledano { get; set; }
    
        public virtual Korisnik Korisnik { get; set; }
    }
}
