//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Spedicija
{
    using System;
    using System.Collections.Generic;
    
    public partial class NalogZaUtovar
    {
        public int IdNalog { get; set; }
        public string BrojNaloga { get; set; }
        public Nullable<int> IdSubjekt { get; set; }
        public string Izvoznik { get; set; }
        public string Napomena { get; set; }
        public string VrstaRobe { get; set; }
        public string BrutoTezina { get; set; }
        public string IzvoznaCarina { get; set; }
        public Nullable<int> IdDnevnik { get; set; }
    
        public virtual DnevnikPrevoza DnevnikPrevoza { get; set; }
        public virtual Subjekt Subjekt { get; set; }
    }
}
