//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Spedicija
{
    using System;
    using System.Collections.Generic;
    
    public partial class Notes
    {
        public int IdNotes { get; set; }
        public System.DateTime Datum { get; set; }
        public string Tekst { get; set; }
        public string Korisnik { get; set; }
    }
}
