//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Spedicija
{
    using System;
    using System.Collections.Generic;
    
    public partial class PonudaUsloviPrevoza
    {
        public int IdPodudaUslovi { get; set; }
        public int IdPonuda { get; set; }
        public int IdUsloviPrevoza { get; set; }
    
        public virtual Ponuda Ponuda { get; set; }
        public virtual UsloviPrevoza UsloviPrevoza { get; set; }
    }
}
