//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Spedicija
{
    using System;
    using System.Collections.Generic;
    
    public partial class StatusPrevoza
    {
        public int IdStatusPrevoza { get; set; }
        public string NazivStatusa { get; set; }
        public bool Aktivan { get; set; }
    }
}
