//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Spedicija
{
    using System;
    using System.Collections.Generic;
    
    public partial class Troskovi
    {
        public int IdTroskovi { get; set; }
        public Nullable<int> IdDnevnik { get; set; }
        public Nullable<decimal> Iznos { get; set; }
        public Nullable<int> IdValuta { get; set; }
        public string Vrsta { get; set; }
        public Nullable<decimal> StvarniTrosak { get; set; }
    
        public virtual DnevnikPrevoza DnevnikPrevoza { get; set; }
        public virtual Valuta Valuta { get; set; }
    }
}
