//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Spedicija
{
    using System;
    using System.Collections.Generic;
    
    public partial class UsloviPrevoza
    {
        public UsloviPrevoza()
        {
            this.PonudaUsloviPrevoza = new HashSet<PonudaUsloviPrevoza>();
        }
    
        public int IdUslov { get; set; }
        public string Tekst { get; set; }
        public bool Aktivan { get; set; }
    
        public virtual ICollection<PonudaUsloviPrevoza> PonudaUsloviPrevoza { get; set; }
    }
}
