//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Spedicija
{
    using System;
    using System.Collections.Generic;
    
    public partial class Valuta
    {
        public Valuta()
        {
            this.DnevnikPrevoza = new HashSet<DnevnikPrevoza>();
            this.DnevnikPrevoza1 = new HashSet<DnevnikPrevoza>();
            this.Troskovi = new HashSet<Troskovi>();
            this.VozacDnevnica = new HashSet<VozacDnevnica>();
            this.Ponuda = new HashSet<Ponuda>();
            this.VozacTroskovi = new HashSet<VozacTroskovi>();
        }
    
        public int IdValuta { get; set; }
        public string NazivValute { get; set; }
        public string OznakaValute { get; set; }
        public Nullable<decimal> UKM { get; set; }
        public Nullable<System.DateTime> DatumZapisa { get; set; }
    
        public virtual ICollection<DnevnikPrevoza> DnevnikPrevoza { get; set; }
        public virtual ICollection<DnevnikPrevoza> DnevnikPrevoza1 { get; set; }
        public virtual ICollection<Troskovi> Troskovi { get; set; }
        public virtual ICollection<VozacDnevnica> VozacDnevnica { get; set; }
        public virtual ICollection<Ponuda> Ponuda { get; set; }
        public virtual ICollection<VozacTroskovi> VozacTroskovi { get; set; }
    }
}
