//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Spedicija
{
    using System;
    using System.Collections.Generic;
    
    public partial class VozacDnevnica
    {
        public VozacDnevnica()
        {
            this.DnevnicaDetail = new HashSet<DnevnicaDetail>();
        }
    
        public int IdVozacDnevnica { get; set; }
        public int IdVozac { get; set; }
        public int Mjesec { get; set; }
        public int Godina { get; set; }
        public Nullable<decimal> Plata { get; set; }
        public Nullable<int> IdValuta { get; set; }
    
        public virtual ICollection<DnevnicaDetail> DnevnicaDetail { get; set; }
        public virtual Valuta Valuta { get; set; }
        public virtual Vozaci Vozaci { get; set; }
    }
}
