//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Spedicija
{
    using System;
    using System.Collections.Generic;
    
    public partial class VoziloPodsjetnik
    {
        public int IdVoziloPodsjetnik { get; set; }
        public int IdVozilo { get; set; }
        public string Vrsta { get; set; }
        public System.DateTime DatumIzrade { get; set; }
        public System.DateTime DatumPodsjetnika { get; set; }
    
        public virtual Vozilo Vozilo { get; set; }
    }
}
